[package]
name = "tx-lang"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = "2.0"
pest = "2.7.10"
pest_derive = "2.6"

# TODO: should only pick the used features
tokio = { version = "1", features = ["full"] }
